menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Projects', url: '/projects'}
- {name: 'Posts', url: '/posts'}
- {name: 'CV', url: '/cv'}
- {name: 'Life', url: '/life'}
- {name: 'Contact', url: '/contact'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/shirley234'}
- {icon: 'twitter', link: 'https://twitter.com/Shirley70646511'}
- {icon: 'instagram', link: 'https://www.instagram.com/qiaoli_wang/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/qiaoli-wang/'}

contacts:
- {name: 'Dr. Qiaoli Wang', title: 'Research Fellow', department: 'Department of Medical Oncology', institution: 'Dana-Farber Cancer Institute and Harvard Medical School', institution_address: '', phone: '617 6326758', email: 'qiaoli_wang@dfci.harvard.edu', office: 'Dana 1212, 450 Brookline Ave, Boston MA 02215', image: 'assets/img/contact.jpg'}
